//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElMestakbal {
    
    
    public partial class Default {
        
        /// <summary>
        /// TopContentPlace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ElMestakbal.UserControls.TopContentPlace TopContentPlace;
        
        /// <summary>
        /// RadBinaryImagePublicityHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadBinaryImage RadBinaryImagePublicityHeader;
        
        /// <summary>
        /// LastNewsH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ElMestakbal.UserControls.LastNewsH LastNewsH;
        
        /// <summary>
        /// MainNewsPaperPDF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ElMestakbal.UserControls.MainNewsPaperPDF MainNewsPaperPDF;
        
        /// <summary>
        /// Slideshow2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ElMestakbal.UserControls.Slideshow Slideshow2;
        
        /// <summary>
        /// leftColu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ElMestakbal.UserControls.leftColu leftColu1;
        
        /// <summary>
        /// leftColuRibbon1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ElMestakbal.UserControls.leftColuRibbon leftColuRibbon1;
        
        /// <summary>
        /// ListNews1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ElMestakbal.UserControls.ListNews ListNews1;
    }
}
